// Generated by gencpp from file apriltags_ros/MetaPose.msg
// DO NOT EDIT!


#ifndef APRILTAGS_ROS_MESSAGE_METAPOSE_H
#define APRILTAGS_ROS_MESSAGE_METAPOSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace apriltags_ros
{
template <class ContainerAllocator>
struct MetaPose_
{
  typedef MetaPose_<ContainerAllocator> Type;

  MetaPose_()
    : pose()
    , px(0.0)
    , py(0.0)
    , detected(false)  {
    }
  MetaPose_(const ContainerAllocator& _alloc)
    : pose(_alloc)
    , px(0.0)
    , py(0.0)
    , detected(false)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef double _px_type;
  _px_type px;

   typedef double _py_type;
  _py_type py;

   typedef uint8_t _detected_type;
  _detected_type detected;





  typedef boost::shared_ptr< ::apriltags_ros::MetaPose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::apriltags_ros::MetaPose_<ContainerAllocator> const> ConstPtr;

}; // struct MetaPose_

typedef ::apriltags_ros::MetaPose_<std::allocator<void> > MetaPose;

typedef boost::shared_ptr< ::apriltags_ros::MetaPose > MetaPosePtr;
typedef boost::shared_ptr< ::apriltags_ros::MetaPose const> MetaPoseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::apriltags_ros::MetaPose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::apriltags_ros::MetaPose_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace apriltags_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'apriltags_ros': ['/home/hal/workspace/src/apriltags_ros/apriltags_ros/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::apriltags_ros::MetaPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::apriltags_ros::MetaPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::apriltags_ros::MetaPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::apriltags_ros::MetaPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::apriltags_ros::MetaPose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::apriltags_ros::MetaPose_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::apriltags_ros::MetaPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2492d463eda8532269b3de2720ad7343";
  }

  static const char* value(const ::apriltags_ros::MetaPose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2492d463eda85322ULL;
  static const uint64_t static_value2 = 0x69b3de2720ad7343ULL;
};

template<class ContainerAllocator>
struct DataType< ::apriltags_ros::MetaPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "apriltags_ros/MetaPose";
  }

  static const char* value(const ::apriltags_ros::MetaPose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::apriltags_ros::MetaPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose pose\n\
float64 px\n\
float64 py\n\
bool detected\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::apriltags_ros::MetaPose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::apriltags_ros::MetaPose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose);
      stream.next(m.px);
      stream.next(m.py);
      stream.next(m.detected);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MetaPose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::apriltags_ros::MetaPose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::apriltags_ros::MetaPose_<ContainerAllocator>& v)
  {
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "px: ";
    Printer<double>::stream(s, indent + "  ", v.px);
    s << indent << "py: ";
    Printer<double>::stream(s, indent + "  ", v.py);
    s << indent << "detected: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.detected);
  }
};

} // namespace message_operations
} // namespace ros

#endif // APRILTAGS_ROS_MESSAGE_METAPOSE_H
